### ISSUE TITLE
multiple inputs

### ISSUE THREAD

**Issue by RogierQ** [PerMalmberg/node-red-contrib-boolean-logic#1]
When connected 3 inputs to a 2 input AND node it only works after a second input signal.
For example:
I have 3 buttons, when 2 buttons are pressed i want a TRUE
When i push button 1 and 2 i get TRUE
When i push button 2 and 3 i get nothing, when i press again i get a TRUE

Is this how it should work?
For me it is not solving my problem the but then i have to look at another solution

**Comment by PerMalmberg** [comment]
Connecting three outputs to a a 2-input AND makes no sense and is not something that will be supported.
