### ISSUE TITLE
3 input OR

### ISSUE THREAD

**Issue by gadjet** [PerMalmberg/node-red-contrib-boolean-logic#2]
Hi,
I've got three Bigtimer node running and each outputs a 0 or a 1 every minute and I fedd the thre outputs into a 3 input OR node but it doesn't work it stays at unknown, if I feed the same three output into a debug node it works and states true, any ideas what I'm doing wrong?

![image](https://cloud.githubusercontent.com/assets/1810366/23628970/0f17b4fe-02ae-11e7-8c7b-a9912885b0cd.png)

**Comment by PerMalmberg** [comment]
All three connected outputs must have different topics, have you made sure that is the case?

**Comment by gadjet** [comment]
I will double check but I assumed if the debug node worked then then the logic node would work with the same inputs

**Comment by PerMalmberg** [comment]
The debug node only looks at the payload, these components needs to separate the inputs to function as intended.

**Comment by gadjet** [comment]
OK, the topic is always "status" from each bigtimer so this won't work for me.

Thanks

**Comment by PerMalmberg** [comment]
Change the topic on the incoming messages, there are components for that. 

What you are experiencing is the problem with Node-Red - only a single input. My components are a workaround for that, but they need to be able to separate incoming messages otherwise they will all look to come from the same source (topic).

**Comment by gadjet** [comment]
Yes, thanks, I was thinking along the same lines myself.

**Comment by gadjet** [comment]
Took your advice and changed each topic and all works well now. Thanks
