### ISSUE TITLE
Gates in chain

### ISSUE THREAD

**Issue by GeoffreyPkz** [PerMalmberg/node-red-contrib-boolean-logic#4]
Hello,

I would like to know why when i put several gate in chain ( a more complex logic circuit), i'm not able to make some gates work (unknown logic status). It happens when I create another gates after the result of two And's gates. (I had parameter gates with proper entries).

Thanks

**Comment by PerMalmberg** [comment]
Based on the little information provided, that happens when the previous gates don't have a known output, because they in turn have unknown input levels.
