### ISSUE TITLE
Unknown Status

### ISSUE THREAD

**Issue by odenisnobre** [PerMalmberg/node-red-contrib-boolean-logic#5]
Hi,

I am testin this node and node-red show is follow status:
![image](https://user-images.githubusercontent.com/8119694/59300845-8d7f6500-8c66-11e9-9e18-2df2a95e54d8.png)

**Comment by PerMalmberg** [comment]
You haven't actually stated a question, but I think you are asking for why it is showing unknown status. If so, please read https://github.com/PerMalmberg/node-red-contrib-boolean-logic/blob/master/README.md#booleanlogic
