### ISSUE TITLE
reset to false

### ISSUE THREAD

**Issue by droneman83** [PerMalmberg/node-red-contrib-boolean-logic#8]
Hi Per
i have got a small issue with the bollean logic node, i hope maby you have way to get around on it.
once the state off the node is true, it do pass a message as expected. but once it is on i like to reset the node to false state, I have tried many ways to reset the node with reset node, change node, attached it with false boolean nodes. but every time this kind of nodes hit inbound on logic node it pass at false message to the node (so it is open again and agian), is it prossible to set a timer to set it to false or another way to close messages go throe??

**Comment by PerMalmberg** [comment]
Hi @droneman83 

I'm sorry, but I don't understand what you're asking for. Can you explain further?
